controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api:
    resource:
        path: ../src/Controller/API/
        namespace: App\Controller\API
    prefix: /api
    type: attribute
